@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Property owner" as Owner
participant ":System" as sys

activate Owner

    Owner -> sys : chooses the agency
    activate sys

    sys -> Owner : gives the chosen agency to the owner
    deactivate sys

    Owner -> sys : chooses the responsible agent
    activate sys

    sys -> Owner : gives the chosen agent to the owner
    deactivate sys

    Owner -> sys : contacts agent to sell or rent a property
    activate sys

    sys --> Owner : requests data
    deactivate sys

    Owner -> sys :  types requested data (area in m^2, location, photos, distance from city center, \nthe requested price, number of bedrooms, number of bathrooms, number of parking spaces, \navailable equipment (central heating and/or airconditioning, \nthe existence of a basement and/or inhabitable loft, sun exposure)
    activate sys

    sys --> Owner : displays operation success
    deactivate sys

@enduml