@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction


class PublishAnnouncementUI


class PublishAnnouncementController {
    + publishAnnouncementController(propertyTypeRepository,announcementRepository)
    + getAnnouncements()
    + publishAnnouncement(propertyType, description, cost, informalDescription,\ntechnicalDescription, durationOfAnnouncement, designation)
}

PublishAnnouncementUI .> PublishAnnouncementController

class Repositories {
-Repositories()

+getInstance():Repositories
+getAnnouncementRepository()
+getPropertyRepository()
+getOwnerIdentityRepository
+getTypeComissionRepository

}

class AnnouncementRepository {
    + getAnnouncements()
}

class PropertyTypeRepository{
    + getPropertyType()
}

class OwnerIdentityRepository{
+getOwnerIdentity()
}

class TypeComissionRepository{
+ getTypeCommission()
}





class Property {
    - double area
    - int distanceFromTheCityCenter

    +Property(area, distanceFromTheCityCenter)
}

class Photos{
    - String URI
}

class House {
    - Boolean existenceOfBasement : false
    - Boolean existenceOfInhabitableLoft : false

    +House(existenceOfBasement, existenceOfInhabitableLoft)
}

class Residence {
 - int numberOfBedrooms : 0
 - int numberOfBathrooms : 0
 - int numberOfParkingSpaces : 0

    +Residence(numberOfBedrooms, numberOfBathrooms, numberOfParkingSpaces)
}

class SunExposure {
    - String direction

    +SunExposure(direction)
}

class AvailableEquipment {
    - String typeOfEquipment

    +AvailableEquipment(typeOfEquipment)
}





class Owner{
+String name
+int tax number
+int phone number
+String email

-getName()
-getEmail()
-getPhoneNumber()
-getTaxNumber()
}

class Address {
    -String streetName
    -int zipCode : 0

    +verifyZipCode()
    +getCity()
    +getDistrict()
    +getState()
    +Address(state, district, city, street, zipCode)

}

class City {
    - String cityName

    -getCityName()
}

class District {
    - String districtName

    -getDistrictName()
}

class State {
    - String stateName

    -getStateName()
}






class Comission{
     - double percentage
     - double staticValue

    + calculateFinalComission()
}


class Rent {
    - int durationOfContract: 0

    +getFinalComission()
    +calculateTotalPrice()
}

class Announcement {
    - String initialDate
    - String finalDate
    - String contractType

    +getOwner()
    +PublishedAnnouncement(initialDate, finalDate, AnnouncementRequest)
}

class Business {
    - double requestedPrice : 0

    +getFinalComission()
    +calculatePriceWithComission()
}

class Repositories
{
    + getAnnouncementRepository()
}



PublishAnnouncementController .> Repositories : repositories
Repositories --> Repositories :instance
Repositories --> OwnerIdentityRepository : ownerIdentity
Repositories --> TypeComissionRepository : comission
Repositories --> AnnouncementRepository : announcement
Repositories --> PropertyTypeRepository : propertyType



PropertyTypeRepository --> Property
Residence <|-- House
Property <|-- Residence
Property "1" -- "1..30" Photos: has >
SunExposure "1" --- "*" House: contains <
AvailableEquipment "*" -- "1" Residence: contains <




City "1"-- "*" Address: is in <
District "1"-- "*" City: is in <
State "1"-- "*" District: is in <
Owner "1" --- "1" Address: has >
OwnerIdentityRepository ..> Owner
Owner --> Property



TypeComissionRepository --> Comission
Comission "1" --- "1" Agent: defines <
Comission "1" --- "1" Business: contains <
Owner "1" --- "1" Business: requests >
Property "1" --- "1" Business: has a <
Announcement "1" --- "1" Business: has >
Announcement "1" --- "1" Property: has a >
Announcement "*" --- "1" Agent: publishes <
Business <|--- Rent


@enduml