@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Agent" as agent
participant ":CreateTaskUI" as UI
participant ":AnnouncementToPublishController" as publish
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "announcementRepository:\nAnnouncementRepository" as AnnouncementRepository
participant "PropertyRepository\n:PropertyRepository" as Pr
participant "Announcement\n:Announcement" as Announcement

        activate agent

    agent -> UI : asks to publish an annoucement to publish

        activate UI

    UI -> publish** : create

    UI -> publish : getAnnouncement()

        activate publish

    publish -> RepositorySingleton : getInstance()

        activate RepositorySingleton

    RepositorySingleton --> publish: repositories

        deactivate RepositorySingleton

    publish -> PLAT : getAnnouncementRepository()

        activate PLAT

    PLAT --> publish: announcementRepository

        deactivate PLAT

    publish -> AnnouncementRepository : getAnnouncement()

        activate AnnouncementRepository

    AnnouncementRepository --> publish : Announcement

        deactivate AnnouncementRepository

    publish --> UI : Announcement

        deactivate publish

    UI --> agent : shows announcements list\n and asks to sleect one of them

        deactivate UI

    agent -> UI : selects an announcement to publish

        activate UI

    UI --> agent : requests data

        deactivate UI

    agent -> UI : types requested data [area in m^2, state, district, city\n, street, zip code and distance from city center]

        activate UI

    opt house, apartment

        autonumber 15

        agent -> UI : types requested data [number of bedrooms, number of bathrooms, number of parking spaces, \navailable equipment (central heating and/or airconditioning)]

            opt house

                autonumber 16

                agent -> UI : types requested data [the existence of a basement and/or inhabitable loft, sun exposure \n(North, South, East, West)]

            end
    end

    UI -> UI : savesData [area in m^2, state, district, city, street, zip code and distance from city center]

    opt  house, apartment

        autonumber 18

        UI -> UI : savesData(number of bedrooms, number of bathrooms, number of parking spaces, \navailable equipment (central heating and/or airconditioning))

            opt house

                autonumber 19

                UI -> UI : savesData(the existence of a basement and/or inhabitable loft, sun exposure \n(North, South, East, West))

            end

    end

    UI --> agent : shows requested data

        deactivate UI

    agent -> UI : submits data

        activate UI

    UI -> publish : publishAnnouncement(area in m^2, state, district, city, street, zip code and distance from city center)

        activate publish

    opt  house, apartment

        autonumber 23

        UI -> publish : publishAnnouncement(number of bedrooms, number of bathrooms, number of parking spaces, \navailable equipment (central heating and/or airconditioning))

        opt house

            autonumber 24

            UI -> publish : publishAnnouncement(the existence of a basement and/or inhabitable loft, sun exposure \n(North, South, East, West))

        end

    end

    publish -> Pr : publishAnnouncement(area in m^2, state, district, city, street, zip code and distance from city center)

        activate Pr

    opt  house, apartment

        autonumber 26

        publish -> Pr : publishAnnouncement(number of bedrooms, number of bathrooms, number of parking spaces, \navailable equipment (central heating and/or airconditioning))

        opt house

            autonumber 27

            publish -> Pr : publishAnnouncement(the existence of a basement and/or inhabitable loft, sun exposure \n(North, South, East, West))

        end

    end

    Pr -> Announcement : publishAnnouncement(area in m^2, state, district, city, street, zip code and distance from city center)

            activate Announcement

        opt  house, apartment

            autonumber 29

            Pr -> Announcement : publishAnnouncement(number of bedrooms, number of bathrooms, number of parking spaces, \navailable equipment (central heating and/or airconditioning))

            opt house

                autonumber 30

                Pr -> Announcement : publishAnnouncement(the existence of a basement and/or inhabitable loft, sun exposure \n(North, South, East, West))

            end

        end

            deactivate Announcement

        Pr -> Pr: Announcement(announcement)

            activate Pr

            deactivate Pr

        Pr -> Pr : ValidadeAnnouncement(annoucement)

            activate Pr

            deactivate Pr

        Pr -> Pr : AskForPhotos(annoucement)

            activate Pr

            deactivate Pr

        Pr -->  publish : Photos

            deactivate Pr

        publish --> UI: Photos

            deactivate publish

        UI --> agent : ask to submit photos

            deactivate UI

        loop Sends photos (from 1 up to 30 pictures)

            agent -> UI : sends photos of the property

                activate UI

        end

        loop Sends photos (from 1 up to 30 pictures)

            UI -> publish : sends photos of the property

                activate publish

        end

        loop Sends photos (from 1 up to 30 pictures)

            publish -> Pr : sends photos of the property

                activate Pr

        end

        loop Sends photos (from 1 up to 30 pictures)

            Pr -> Announcement : sends photos of the property

                activate Announcement

        end

            deactivate Announcement

        Pr -> Pr: Announcement(announcement)

            activate Pr

            deactivate Pr

        Pr -> Pr : ValidadeAnnouncement(annoucement)

            activate Pr

            deactivate Pr

        Pr -> Pr : AskForComission(annoucement)

            activate Pr

            deactivate Pr

        Pr -->  publish : Comission

            deactivate Pr

        publish --> UI: Comission

            deactivate publish

        UI --> agent : ask agent to submit the comission type and the needed data

            deactivate UI

        alt percentage

            agent -> UI : inserts the percentage comission

                activate UI

            else value

                agent -> UI: inserts the comission value

        end

        alt percentage

            UI -> publish : inserts the percentage comission

                activate publish

            else value

                UI -> publish: inserts the comission value

        end

        alt percentage

            publish -> Pr : inserts the percentage comission

                activate Pr

            else value

                publish -> Pr: inserts the comission value

        end

        alt percentage

            Pr -> Announcement : inserts the percentage comission

                activate Announcement

            else value

                Pr -> Announcement: inserts the comission value

        end

            deactivate Announcement

        Pr -> Pr: Announcement(announcement)

            activate Pr

            deactivate Pr

        Pr -> Pr : ValidadeAnnouncement(annoucement)

            activate Pr

            deactivate Pr

        Pr -> Pr : AskToValidateTheOperation(annoucement)

            activate Pr

            deactivate Pr

        Pr -->  publish : Validate the Operation

            deactivate Pr

        publish --> UI: Validate the Operation

            deactivate publish

        UI --> agent : ask agent to validate the operation

            deactivate UI

        agent -> UI : validates the operation

            activate UI

        UI --> agent : displays operation success

            deactivate UI
@enduml