@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":CreateTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "taskCategoryRepository:\nTaskCategoryRepository" as TaskCategoryRepository

autonumber 12
-> CTRL : getTaskCategoryByDescription(taskCategoryDescription)

autonumber 12.1

activate CTRL
    group Get Task Category
        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

            RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT : getTaskCategoryRepository()
        activate PLAT

            PLAT -> CTRL : taskCategoryRepository
        deactivate PLAT

        CTRL -> TaskCategoryRepository : getTaskCategoryByDescription(taskCategoryDescription)
        activate TaskCategoryRepository

            TaskCategoryRepository --> CTRL : taskCategory
        deactivate TaskCategoryRepository

    end group

    autonumber 13
    <-- CTRL : taskCategory

deactivate CTRL


@enduml