@startuml

title US011 - Domain Model

skinparam groupInheritance 2
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class PublishedAnnouncement {
    Contract Type
}

class Agent {

}

class Person{
Name
Email
Phone Number
Tax Number
Passport Number
}


class Client{
Password
}

class Address {
Street
Zip Code
}

class AvailableEquipment {
Equipment
}


class Business {
Total price
}


class City {
City Name
}

class Comission {
Value
}
'/

class ComissionPercentage {
Percentage Value
}
'/


class District {
District Name
}


class House {
Basement
Inhabitable Loft
}


class Photos {
URI
}

class Property {
Area
Distance from the city center
}


class Rent {
Duration of contract
}


class Residence {
Number of Bedrooms
Number of Bathrooms
Number of Parking Spaces
}


class State {
State Name
}

class SunExposure {
Direction
}

class TypeOfProperty {
Type
}
class Offer{
    Offer Value
}


Business <|-- Rent

Comission "1" -- "1" Business : contains <
ComissionPercentage  --|> Comission

House "1" --- "1" SunExposure : contains >

Property <|--- Residence
Property "*" -right- "1" Address : has >
PublishedAnnouncement "1" -left- "1" Business : has <
Property "1" -- "1..30" Photos : has >
PublishedAnnouncement "*" --- "*" Property: advertises >

Residence "1" --- "*" AvailableEquipment : contains >
Residence <|--- House

District "1" -left- "*" City : has >
State "1" -left- "*" District : has >
City "1" -left- "*" Address : has >

TypeOfProperty "1" -right- "1" Property : defines >
Person <|-- Client

Client "1" -left "*" Offer : makes >
Agent "1" -right "*" Offer : accepts/declines > 
PublishedAnnouncement "1"  -up-- "*" Offer : has >
@enduml