@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Organization Employee" as Employee
participant ":System" as System

activate Employee

Employee -> System : Asks to create a new task
activate System

    System --> Employee : requested data (reference, designation, \ninformal description, technical description,\nduration, cost)
deactivate System

Employee -> System : Types requested data
activate System

    System --> Employee : shows task category list and asks to select one
deactivate System
Employee -> System : Selects a task category
activate System

    System --> Employee : shows all data
deactivate System

@enduml