@startuml

left to right direction

 :System Administrator: as admin
 :Agent: as agent
 :Unregistered user: as user
 :Owner: as owner
 :Client: as client
 :network Manager: as manager
 :store Manager: as smanager
 package System {
   usecase "UC01: As an unregistered user, I want to display listed properties." as UC1
   usecase "UC02: As an agent, I can publish any sale announcement on the system, for example received through a phone call." as UC2
   usecase "UC03: As a system administrator, I want to register a new employee." as UC3
   usecase "UC04: As an owner, I intend to submit a request for listing a property sale or rent, choosing the responsible agent." as UC4
   usecase "UC05: As a system administrator, I want to register a store." as UC5
   usecase "UC06: As a system administrator, I want to specify states, districts and cities in the system." as UC6
   usecase "UC07: As an unregistered user, I want to register in the system to buy, sell or rent properties." as UC7
   usecase "US08: As an agent, I intend to see the list of property announcement requests\nmade to myself, so that I can post the announcement" as UC8
   usecase "US09: As a client, I want to leave a message to the agent to schedule a visit to a property of my interest" as UC9
   usecase "US10: As a client, I place an order to purchase the property, submitting the order amount" as UC10
   usecase "US11: As an agent, I want to list real estate purchase orders to accept or decline a purchase order for a property.\nAfter accepting or declining, an email notification should be sent to the customer" as UC11
   usecase "US12: As a system administrator, I want to import information from a legacy system\nthat has been in use in several agencies" as UC12
   usecase "US13: As a network manager, I want to list all employees working in every store of the network" as UC13
   usecase "US14: As a client, I want to read the response for the appointment requests, to accept or reject it" as UC14
   usecase "US15: As an agent, I intend to list all booking requests for properties managed by me. " as UC15
   usecase "US16: As an agent, when viewing a booking request, I want to respond to the user that scheduled the visit." as UC16
   usecase "US17: As a network manager, I want to list all deals made." as UC17
   usecase "US18: As a store manager, I intend to analyse the deals (only sale of houses and apartments) made.\nIn particular, I intend to compare property sale values with the forecast values. \nThe prediction of the value of the business/property must\nbe estimated based on the characteristics of the property and using linear and multilinear regression algorithms." as UC18
   usecase "US19: As a network manager, I want to divide the set of all stores into two subsets, so that the \ntotal number of properties of the stores between the two subsets is the closest possible." as UC19
   usecase "US20: As a client, I want to read the response for the appointment request, to accept or reject it." as UC20
   usecase "US21: As an agent, at the end of the visit, I want to register the visit and the opinion about the business." as UC21
 }
 admin --> UC3
 admin --> UC5
 admin --> UC6
 admin --> UC12

 user --> UC1
 user --> UC7

 agent --> UC2
 agent --> UC8
 agent --> UC11
 agent --> UC15
 agent --> UC16
 agent --> UC21

 owner --> UC4

 client --> UC9
 client --> UC10
 client --> UC14
 client --> UC20

 manager --> UC13
 manager --> UC17
 manager --> UC19

smanager --> UC18


@enduml