@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "System Administrator" as Admin
participant ":System" as System

activate Admin

    Admin -> System : asks to register a store
    activate System

        System --> Admin : requests the necessary data (id, designation/name, state, district, city, \nstreet, zip code, email address and phone number)
    deactivate System

    Admin -> System : types requested data
    activate System

        System --> Admin : shows inserted data and asks for confirmation
    deactivate System

    Admin -> System : confirms
    activate System

        System --> Admin : displays operation success
    deactivate System

@enduml