@startuml

title US001 - Domain Model

skinparam groupInheritance 2
skinparam monochrome true
skinparam linetype polyline
hide methods
hide circle


class Address {
Street
Zip Code
}

class AvailableEquipment {
Equipment
}


class Business {
Type of Business
Total price
}


class City {
City Name
}

/'class Comission {
Static Value
}
'/

/'class ComissionPercentage {
Percentage Value
}
'/


class District {
District Name
}


class House {
Basement
Inhabitable Loft
}


class Photos {
Description
URI
}

class Property {
Area
Distance from the city center
}

class PublishedAnnouncement {
Initial Date
Final Date

}


class Rent {
Duration of the contract
}


class Residence {
Number of Bedrooms
Number of Bathrooms
Number of Parking Spaces
}


class State {
State Name
}

class SunExposure {
Direction
}


class UnregisteredUser {
}



Business <|-- Rent

City "1" --- "*" Address : is in <
'Comission "1" -right- "1" Business : contains <

District "1" --- "*" City : is in <

House "*" --- "1" SunExposure : has <

Property <|--- Residence
Property "*" -left- "1" Address : has <
Property "1" --- "1" Business : has <
Property "1" -right- "*" Photos : has >
PublishedAnnouncement "*" --- "*" Property: advertises >

Residence "*" --- "1" AvailableEquipment : has <
Residence <|--- House

State "1" --- "*" District : is in <

UnregisteredUser "*" --- "*" PublishedAnnouncement: displays >

@enduml