@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber
participant ":OfferDecisionController" as controller
participant "offerRepository\n:OfferRepository" as offerrepository
participant "Offer\n:Offer" as offer
participant "EmailServices\n:EmailServices" as email



activate controller
        controller -> email : String emailServiceClass = properties.getProperty("emailService");
        activate email
        controller --> controller : emailService = (EmailService) serviceClass.newInstance();
        controller -> email : sendVisualizedEmail(String email, String subject, String body)
        email --> email : emailService.sendEmail(email, subject, body);
        deactivate email
        deactivate controller


@enduml