@startuml

skinparam groupInheritance 2

left to right direction

class UnregisteredUser {
}

class Property {
- Area
- Photos
- Distance from the city center
- The requested price
- Address
}


class Residence {
- Number of Bedrooms
- Number of Bathrooms
- Number of Parking Spaces
- AvailableEquipment
 }


class House {
- Basement
- Inhabitable Loft
- SunExposure
}


class SunExposure {
- Direction
}


class Address {
- Street
- City
- County
- State
- Zip Code
}


class AvailableEquipment {
- Equipment
}


UnregisteredUser "*" - "*" Property: consults >

Residence "*" --- "1" Property: is a >
Address "*" --- "1" Property : part of >

AvailableEquipment "*" --- "1" Residence : part of >
House "*" --- "1" Residence : is a >

SunExposure "*" --- "1" House : part of >

@enduml