@startuml

skinparam groupInheritance 2

class UnregisteredUser {
}

class Property {
- Area
- Photos
- Distance from the city center
- The requested price
- Address
}


class Residence {
- Number of Bedrooms
- Number of Bathrooms
- Number of Parking Spaces
- AvailableEquipment
 }


class House {
- Basement
- Inhabitable Loft
- SunExposure
}


class SunExposure {
- Direction
}


class Address {
- Street
- City
- County
- State
- Zip Code
}


class AvailableEquipment {
- Equipment
}


UnregisteredUser "*" -- "*" Property: consults >

Property "*" --- "1" Residence: is a <
Property "*" --- "1" Address : part of <

Residence "*" --- "1" AvailableEquipment : part of <
Residence "*" --- "1" House : is a <

House "*" --- "1" SunExposure : part of <

@enduml