@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US010 - Sequence Diagram Partial - Get Published Announcement

participant ":PlaceOfferController" as Controller
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as Repositories
participant "publishedAnnouncementRepository\n:PublishedAnnouncementRepository" as PublishedAnnouncementRepository

autonumber 3

-> Controller : getPublishedAnnouncement()
activate Controller

group getPublishedAnnouncement

Controller -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> Controller: repositories
deactivate RepositorySingleton

Controller -> Repositories : getPublishedAnnouncementRepository()
activate Repositories

Repositories --> Controller: PublishedAnnouncementRepository
deactivate Repositories

Controller -> PublishedAnnouncementRepository : getPublishedAnnouncement()
activate PublishedAnnouncementRepository

PublishedAnnouncementRepository --> Controller : PublishedAnnouncementList
deactivate PublishedAnnouncementRepository

end

<-- Controller : PublishedAnnouncementList
deactivate Controller
@enduml