@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US010 - Sequence Diagram Partial - Create Offer

participant ":PlaceOrderController" as Controller
participant "repositories\n:Repositories" as Repositories
participant "authenticationRepository\n:AuthenticationRepository" as AuthenticationRepository
participant "offerRepository\n:OfferRepository" as OfferRepository
participant "Offer" as Offer

autonumber 15

-> Controller : createOffer(orderAmount)
activate Controller

group Create Offer

Controller -> Repositories : getAuthenticationRepository()
activate Repositories

Repositories --> Controller : authenticationRepository
deactivate Repositories

Controller -> AuthenticationRepository : getCurrentUserSession()
activate AuthenticationRepository

AuthenticationRepository --> Controller : getCurrentUserSession
deactivate AuthenticationRepository

Controller -> Offer : Offer(user, publishedAnnouncement, orderAmount)
activate Offer

Offer --> Controller : offer
deactivate Offer

Controller -> Repositories : getOfferRepository()
activate Repositories

Repositories --> Controller : getOfferRepository
deactivate Repositories

'Controller -> OfferRepository : checkExistingOffer(offer)
'activate OfferRepository
'
'OfferRepository --> Controller : checkExistingOffer
'deactivate OfferRepository
'
'    opt if checkExistingOffer == true
'
'       Controller --> System : checkExistingOffer
'
'       System --> Client : asks the user to wait until the pending request is either accepted or rejected
'
'    end

Controller -> OfferRepository : addOffer(offer)
activate OfferRepository

OfferRepository --> Controller : addOffer
deactivate OfferRepository

end

<-- Controller : createOffer

@enduml