@startuml

'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto
'skinparam classAttributeIconSize 0
'left to right direction

title US13 - Class Diagram

class State {
    - String stateName
    + List<District> districts
}

class District {
    - String districtName
    + List<City> cities
}

class City {
    - String cityName

}

class Address {
    -String streetName
    -int zipCode
}

class Contacts {
    -String phoneNumber
    -String email
}

class Repositories {
    -Repositories()
    +getInstance():Repositories
    +getStateRepository()
}

class Store {
    -int id
    -String designation
    +addStore(store)
    +validateStore(store)
}

class RegisterStoreController {
    +getStates()
    +getDistrictByDescription(state)
    +getCityByDescription(district)
    +registerStore(id, designation/name, state, district, city, \nstreet, zip code, email address and phone number)
    -getStateRepository()
}

class StateRepository {
    +getStates()
    +getDistrictByDescription(state)
    +getCityByDescription(district)
}

class RegisterStoreUI {

}

Repositories -> Repositories:instance
Repositories --> StateRepository: stateRepository
RegisterStoreController ..> Repositories : repositories
RegisterStoreController ..> StateRepository : StateRepository
RegisterStoreController ..> Store : Store
RegisterStoreUI .right.> RegisterStoreController
Address "1" -left-> "*"  Store : is located at
State "1" -up- "*" Address: has >
District "1" -right- "*" City : has >
State "1" -right- "*" District : has >
Contacts "1" -up--> "1" Store: has

@enduml