@startuml

title US05 - Domain Model

skinparam groupInheritance 2
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class SystemAdministrator

class Address

class State

class District

class City

class Contacts

class Store

class SystemAdministrator {

}

class Employee {
    Name
    ID
    Tax Number
    Role
}

class Contacts {
    Phone Number
    Email Adress
}

class Store {
    ID
    Designation
}

class State {
    State name
}

class District {
    District name
}

class City {
    City name
}

class Address {
    Street
    Zip Code
}

Store "*" -up-- "1" Address: is located at >
Store "*" -right-- "1" Contacts: has >
SystemAdministrator "1" -right-- "*" Store: registers >
District "1" -left-- "*" State : has >
State "1" -left-- "*" City : has >
City "1" -left-- "*" Address : has >

Employee <|--- SystemAdministrator

@enduml