@startuml

title US001 - Class Diagram


skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

'skinparam linetype orto
'skinparam monochrome true
'left to right direction


class Address {
    - String streetName
    - int zipCode : 0

    +verifyZipCode()
    +getCity()
    +getDistrict()
    +getState()
    +Address(state, district, city, street, zipCode)
}

class AvailableEquipment {
    - String typeOfEquipment

    +AvailableEquipment(typeOfEquipment)
}


class Business {
    - double requestedPrice : 0

    +getFinalComission()
    +calculatePriceWithComission()
}


class City {
    - String cityName
}

class Comission {
    - double percentage : 0
    - double staticValue : 0

    + calculateFinalComission()
}


class District {
    - String districtName
}


class House {
    - Boolean existenceOfBasement : false
    - Boolean existenceOfInhabitableLoft : false

    +House(existenceOfBasement, existenceOfInhabitableLoft)
}


class Photos {
    - String URI
}

class Property {
    - double area : 0
    - int distanceFromTheCityCenter : 0

    +Property(area, distanceFromTheCityCenter)
}

class PublishedAnnouncement {
    - String initialDate
    - String finalDate

    +getAnnouncementRequest()
    +PublishedAnnouncement(initialDate, finalDate, AnnouncementRequest)
}


class Rent {
    - int durationOfContract: 0

    +getFinalComission()
    +calculateTotalPrice()
}


class Residence {
    - int numberOfBedrooms : 0
    - int numberOfBathrooms : 0
    - int numberOfParkingSpaces : 0

    +Residence(numberOfBedrooms, numberOfBathrooms, numberOfParkingSpaces)
}


class State {
    - String stateName
}

class SunExposure {
    - String direction

    +SunExposure(direction)
}


class UnregisteredUser {
}



Business <|-- Rent

City "1" --- "*" Address : is in <
Comission "1" -right- "1" Business : contains <

District "1" --- "*" City : is in <

House "*" --- "1" SunExposure : has <

Property <|--- Residence
Property "*" -left- "1" Address : has <
Property "1" --- "1" Business : has <
Property "1" -right- "*" Photos : has >
PublishedAnnouncement "*" --- "*" Property: advertises >

Residence "*" --- "1" AvailableEquipment : has <
Residence <|--- House

State "1" --- "*" District : is in <

UnregisteredUser "*" --- "*" PublishedAnnouncement: displays >

@enduml