@startuml

'https://plantuml.com/sequence-diagram

autonumber

@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title PublishAnnouncementRequestUI Sequence Diagram (SSD)

autonumber

actor "Agent" as Agent
participant ":PublishAnnouncementRequestUI" as PublishAnnouncementRequestUI
participant ":PublishAnnouncementRequestController" as PublishAnnouncementRequestController
participant ":Repositories" as Singleton
participant "repositories\n:Repositories" as repositories
participant ":ApplicationSession" as AplicationSession
participant "appSession\n:ApplicationSession" as aplicationSession
participant "currentSession\n:UserSession" as UserSession
participant "announcementRequestRepository\n:AnnouncementRequestRepository" as AnnouncementRequestRepository
participant "comissionRepository\n:ComissionRepository" as ComissionRepository
participant ":XMapper" as XMapper
participant "listAnnouncementRequestDto:List<AnnouncementRequestDto>" as listAnnouncementRequestDto
participant "listAnnouncementRequest:List<AnnouncementRequest>" as listAnnouncementRequest
participant "announcementRequestDto:AnnouncementRequestDto" as AnnouncementRequestDto
participant "publishedAnnouncementRequestRepository\n:PublishedAnnouncementRequestRepository" as PublishAnnouncementRepository
participant "employeeRepository\n:EmployeeRepository" as EmployeeRepository


activate Agent

    Agent -> PublishAnnouncementRequestUI : asks to see the list of property announcement request
    activate PublishAnnouncementRequestUI

PublishAnnouncementRequestUI -> PublishAnnouncementRequestController**: create

PublishAnnouncementRequestUI -> PublishAnnouncementRequestController : getAnnouncementRequestList()
activate PublishAnnouncementRequestController

PublishAnnouncementRequestController -> PublishAnnouncementRequestController: getEmployeeFromSession

PublishAnnouncementRequestController -> AplicationSession: getInstance()
activate AplicationSession

AplicationSession --> PublishAnnouncementRequestController:appSession
deactivate AplicationSession

PublishAnnouncementRequestController -> aplicationSession :getCurrentSession()
activate aplicationSession

aplicationSession --> PublishAnnouncementRequestController:currentSession
deactivate aplicationSession

PublishAnnouncementRequestController -> UserSession :email = getUserEmail()
activate UserSession

UserSession --> PublishAnnouncementRequestController:email
deactivate UserSession

PublishAnnouncementRequestController ->EmployeeRepository:getEmployeeByEmail()
activate EmployeeRepository

EmployeeRepository --> PublishAnnouncementRequestController:employeeByEmail
deactivate EmployeeRepository




PublishAnnouncementRequestController -> Singleton: getInstance()
activate Singleton

Singleton --> PublishAnnouncementRequestController: repositories
deactivate Singleton

PublishAnnouncementRequestController -> repositories: getAnnouncementsRequestRepository()
activate repositories

repositories --> PublishAnnouncementRequestController:announcementRepository
deactivate repositories

PublishAnnouncementRequestController -> AnnouncementRequestRepository:getAnnouncementRequestListByAgent(employeeByEmail)
activate AnnouncementRequestRepository

AnnouncementRequestRepository --> PublishAnnouncementRequestController:announcementsRequestListByAgent
deactivate AnnouncementRequestRepository

PublishAnnouncementRequestController -> XMapper: toDto(announcementsRequestListByAgent)
activate XMapper

XMapper --> listAnnouncementRequestDto**: create()

loop

XMapper -> listAnnouncementRequest :agent = getAgent()
activate listAnnouncementRequest

XMapper -[hidden]> listAnnouncementRequest
deactivate listAnnouncementRequest

XMapper -> listAnnouncementRequest: property = getProperty()
activate listAnnouncementRequest

XMapper -[hidden]> listAnnouncementRequest
deactivate listAnnouncementRequest

XMapper -> listAnnouncementRequest: typeOfBusiness = getTypeOfBusiness()
activate listAnnouncementRequest

XMapper -[hidden]> listAnnouncementRequest
deactivate listAnnouncementRequest

XMapper -> listAnnouncementRequest: propertyType = getPropertyType()
activate listAnnouncementRequest

XMapper -[hidden]> listAnnouncementRequest
deactivate listAnnouncementRequest

XMapper -> listAnnouncementRequest: business = getBusiness()
activate listAnnouncementRequest

XMapper -[hidden]> listAnnouncementRequest
deactivate listAnnouncementRequest

XMapper -> listAnnouncementRequest: date = geDate()
activate listAnnouncementRequest

XMapper -[hidden]> listAnnouncementRequest
deactivate listAnnouncementRequest


XMapper -> listAnnouncementRequest: durationOfContract = geDate()
activate listAnnouncementRequest

XMapper -[hidden]> listAnnouncementRequest
deactivate listAnnouncementRequest

XMapper -> XMapper : announcementsRequestDto = toDto(agent,property,typeOfBusiness,propertyType,business,date,durationOfContract)
activate XMapper

deactivate XMapper

XMapper --> AnnouncementRequestDto**: create(...)

XMapper -> listAnnouncementRequestDto: add(announcementRequestDto)
activate listAnnouncementRequestDto

deactivate listAnnouncementRequestDto
end

XMapper --> PublishAnnouncementRequestController: listAnnouncementRequestDto

PublishAnnouncementRequestController --> PublishAnnouncementRequestUI:listAnnouncementRequestDto
deactivate PublishAnnouncementRequestController

     PublishAnnouncementRequestUI --> Agent : shows list of announcement request responsible for that agent and asks to select one
        deactivate PublishAnnouncementRequestUI

            Agent -> PublishAnnouncementRequestUI : selects one announcement request
            activate PublishAnnouncementRequestUI


alt Accepts Announcement Request
 PublishAnnouncementRequestUI -> PublishAnnouncementRequestController : getTypeComission()
           activate PublishAnnouncementRequestController

           PublishAnnouncementRequestController -> Singleton : getInstance()
           activate Singleton

           Singleton --> PublishAnnouncementRequestController : repositories
           deactivate Singleton

           PublishAnnouncementRequestController -> repositories : getTypeComissionRepository()
           activate repositories

           repositories --> PublishAnnouncementRequestController : typeComissionRepository
           deactivate repositories

               PublishAnnouncementRequestController -> ComissionRepository : getTypeComission()
                activate ComissionRepository

                ComissionRepository --> PublishAnnouncementRequestController : Type Comission
                deactivate ComissionRepository

           PublishAnnouncementRequestController --> PublishAnnouncementRequestUI : Type Comission
           deactivate PublishAnnouncementRequestController




System --> Agent:shows the comissions available
deactivate System

Agent -> System:select the respective comission
deactivate System
end

alt reject Announcement Request
System --> Agent:requests data(messageJustification)
deactivate System

Agent -> System:types request data
activate System
end

PublishAnnouncementRequestUI --> Agent:shows the infomation of and asks for confirmation
deactivate PublishAnnouncementRequestUI

 Agent -> PublishAnnouncementRequestUI : submits data
    activate PublishAnnouncementRequestUI

alt Accepts Announcement Request
PublishAnnouncementRequestUI -> PublishAnnouncementRequestController:publishAnnouncementRequest(publishedAnnouncementRequestDescription,comissionDescription)
activate PublishAnnouncementRequestController

PublishAnnouncementRequestController -> PublishAnnouncementRequestController:getAnnouncementRequestByDescription(announcementRequestDescription)
activate PublishAnnouncementRequestController


PublishAnnouncementRequestController -> AnnouncementRequestRepository :getAnnouncementRequestByDescription()
activate AnnouncementRequestRepository

AnnouncementRequestRepository --> PublishAnnouncementRequestController:announcementRequest
deactivate AnnouncementRequestRepository

PublishAnnouncementRequestController--> PublishAnnouncementRequestController:announcementRequest


PublishAnnouncementRequestController -> PublishAnnouncementRequestController:getComissionByDescription(comissionDescription)
activate PublishAnnouncementRequestController

PublishAnnouncementRequestController -> ComissionRepository:getComissionByDescription()
activate ComissionRepository

PublishAnnouncementRequestController <-- ComissionRepository:comission
deactivate ComissionRepository

PublishAnnouncementRequestController --> PublishAnnouncementRequestController:comission

PublishAnnouncementRequestController -> PublishAnnouncementRepository:createPublishedAnnouncement(announcementRequest,comission)
activate PublishAnnouncementRepository

PublishAnnouncementRepository -> PublishedAnnouncement** : createPublishedAnnouncement(name,passport number,tax number \n,email ,telephone number,store\n role,adress)
             PublishAnnouncementRepository -> PublishAnnouncementRepository : addPublishedAnnouncement(publishedAnnouncement)
             activate PublishAnnouncementRepository
             PublishAnnouncementRepository -> PublishAnnouncementRepository : validatePublishedAnnoncement(publishedAnnouncement)
              activate PublishAnnouncementRepository
               PublishAnnouncementRepository --> PublishAnnouncementRepository
               deactivate PublishAnnouncementRepository
                PublishAnnouncementRepository--> PublishAnnouncementRepository
                deactivate PublishAnnouncementRepository


PublishAnnouncementRepository --> PublishAnnouncementRequestController:publishedAnnouncement
deactivate PublishAnnouncementRepository

PublishAnnouncementRequestController --> PublishAnnouncementRequestUI:publishedAnnouncement
end

alt reject Announcement Request
 PublishAnnouncementRequestUI -> PublishAnnouncementRequestUI: sendEmailJustification()

end

        PublishAnnouncementRequestUI --> Agent : displays operation success
    deactivate PublishAnnouncementRequestUI



@enduml
