@startuml
'https://plantuml.com/sequence-diagram

participant ":PublishAnnouncementRequestController" as PublishAnnouncementRequestController
participant "comissionRepository\n:ComissionRepository" as ComissionRepository

autonumber 56

activate PublishAnnouncementRequestController
PublishAnnouncementRequestController -> PublishAnnouncementRequestController:getComissionByDescription(comissionDescription)


Group Get Comission By Description

activate PublishAnnouncementRequestController

activate PublishAnnouncementRequestController

PublishAnnouncementRequestController -> ComissionRepository:getComissionByDescription()
activate ComissionRepository

PublishAnnouncementRequestController <-- ComissionRepository:comission
deactivate ComissionRepository

end
PublishAnnouncementRequestController --> PublishAnnouncementRequestController:comisison

@enduml