@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : asks to publish any sale annoucement
    activate System

        System --> Agent : requests data
    deactivate System

    opt house, apartment or land

        Agent -> System : types requested data (area in m^2, location, photos, distance from city center and the requested price)

        activate System

        else house or apartment

            alt with Bathrooms

                Agent -> System : types requested data (number of bedrooms, number of bathrooms, number of parking spaces)


             else with Available Equipment

                Agent -> System : types requested data (number of bedrooms, number of parking spaces, \navailable equipment (central heating and/or airconditioning))


             else with Bathrooms and Available Equipment

                Agent -> System : types requested data (number of bedrooms, number of bathrooms, number of parking spaces, \navailable equipment (central heating and/or airconditioning))


             else without Bathrooms or Available Equipment

                 Agent -> System : types requested data (number of bedrooms,  number of parking spaces)

            end


        else house

            alt with Sun Exposure

                Agent -> System : types requested data (the existence of a basement and/or inhabitable loft, sun exposure \n(North, South, East, West))


            else without Sun Exposure

                Agent -> System : types requested data (the existence of a basement and/or inhabitable loft)


             end

     end


    System --> Agent : publishes the offer
    deactivate System

    Agent -> System : submits data
    activate System

    System --> Agent : displays operation success
    deactivate System


@enduml