@startuml

skinparam groupInheritance 2
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

class Contacts

class Rent

class Announcement

class AvailableEquipment

class Business

class UnregisteredUser

class SystemAdministrator

class Agent

class Store

class StoreManager

class Owner

class StoreNetworkManager

class House

class SunExposure

class LocationOrAdress

class Employee

class Property

class Residences

class Role

class Comission

class Rent{
duration of contract
price per month
}

class SystemAdministrator{
}

class Employee{
name
id
tax number
role
}

class Agent{

}

class Store{
designation
}

class StoreManager{

}


class Owner{
name
id
number
tax number
email
}

class StoreNetworkManager{
}

class House{
basement
inhabitable loft
}


class SunExposure{
regions
}


class LocationOrAdress{
street
zipCode
City
Country
State
}

class Property {
   area
   photos
   LocationOrAdress
   distance from the city center
   the requested price
}

class Residences{
number of bedrooms
number of bathrooms
number of parking spaces
central heating
air conditioning
}

class UnregisteredUser{
}

class Role{
role
}

class AvailableEquipment{
equipment
}

class Business{
sale
rent
}

class Announcement{
date
}

class Comission{
    type
    value
}

class Contacts{
 Phone number
 Email adress
}


'Properties
SystemAdministrator "1" - "*" Store : registers >

LocationOrAdress "*" --- "1" Store : located at <

Store "1" - "*" Employee : works in <

SystemAdministrator "1" - "*" Employee : registers >

Employee "1" - "1" Role : has >

Employee <|--  StoreNetworkManager

Employee <|--  StoreManager

Employee <|-- Agent

Residences <|--- House
Property <|-- Residences

Property "*" --- "1" Agent: publishes <

AvailableEquipment "*" --- "1" Residences: has >

Business  <|--  Announcement

Business "1" --- "1" Property : have a >

Business "*" --- "1" Comission : contains >

Agent "1" - "1" Comission : defines >

House "*" --- "1" SunExposure : contains >

LocationOrAdress "*" --- "1" Property : located at <

UnregisteredUser "*" --- "*" Property: wants to see >

Business <|-- Rent

Owner "1" ---- "1" Store: contacts >

Owner "1" - "1" LocationOrAdress: has >

Owner "1" -- "1" Contacts: has >

Contacts "1" ----- "1" Store: has <

Employee "1" -- "1" Contacts: has >

Store "*" - "1" StoreNetworkManager  : manages <

@enduml