@startuml

skinparam group 3.0
hide empty members
skinparam ClassFontSize 17
scale 2.5


class UnregisteredUser

class SystemAdministrator

class Agent

class Store

class StoreManager

class Owner

class StoreNetworkManager

class Client

class House

class SunExposure

class LocationOrAdress

class Employee

class Properties

class Residences


class SystemAdministrator{
}

class Employee{
-name
-id
-number
-tax number
-role
}

class Agent{

}

class Store{
-designation
-location
-email
-contact number
}

class StoreManager{

}


class Owner{
-name
-id
-number
-tax number
-email
}

class StoreNetworkManager{
}

class Client{
-name
-type of property
-type of business
-number of rooms
}

class Apartment{
}

class House{
-basement
-inhabitable loft
}


class SunExposure{
-regions
}


class LocationOrAdress{
-street
-adressExtension
-zipCode
}

class Properties{
-area
-location
-photos
-distance from the city center
-the requested price
}

class Residences{
-number of bedrooms
-number of bathrooms
-number of parking spaces
-central heating
-air conditioning
}

class UnregisteredUser{
-type of property
-type of business
-number of rooms
}

'Properties


@enduml