@startuml

left to right direction

class SystemAdministrator

class Agent

class Store

class StoreManager

class StoreNetworkManager

class Owner

class Client

class Customer

class ListOfProprieties

class Apartment

class House

class Land

class SunExposure

class SortingCriteria

class SystemAdministrator {
}

class Agent {
- name
- id
- number
- agency
- tax number
}

class Store {
- name
- location
- email
- number
}

class StoreManager {
- name
- id
- number
- agency
- tax number
}

class StoreNetworkManager {
}

class Owner {
- property characteristics
- requested price
}

class Client {
- name
- type of property
- type of business
- number of rooms
- sorting criteria(price and/or parish)
}

class Customer {
- name
}

class ListOfProprieties {
- area
- location
- photos
- distance from the city center
- the requested price
}

class Apartment {
- number of bedrooms
- number of bathrooms
- number of parking spaces
- central heating
- air conditioning
}

class House {
- basement
- inhabitable loft
- sun exposure (North, South, East, West)
}

class Land {
}

class SortingCriteria {
- price
- parish
}

class SunExposure {
- north
- south
- east
- west
}

SystemAdministrator "1" --- "*" Agent : registers >

SystemAdministrator "1" --- "*" Store: registers >

SystemAdministrator "1" --- "*" StoreManager: registers >

Agent "*" ---- "1" Store : works in >

Store "1" --- "1" StoreManager: is managed >

Store "*" --- "1" StoreNetworkManager:  manages <

Owner "*" --- "1" Store: visit >

Owner "*" -up-- "1" Agent: assigned >

ListOfProprieties "1" --- "1" Agent: publishes <

Client "*" --- "1" ListOfProprieties: consults >

Client "*" --- "1" Agent: requests to schedule visit >

Land "*" --- "1" ListOfProprieties: part of >

House "*" --- "1" ListOfProprieties: part of >

Apartment "*" --- "1" ListOfProprieties: part of >

Agent "1" --- "1" Customer :  accepts offer <

StoreManager "1" --- "*" Agent : evaluates >

SunExposure "*" --- "1" House : part of >

SortingCriteria "*" --- "1" Client : attributes (?) >

@enduml