@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US011 - System Sequence Diagram (SSD)

autonumber

actor "Agent" as agent
participant ":System" as sys

activate agent


agent -> sys : asks for a list of real estate purchase orders for every property
activate sys
sys --> agent : shows the list of purchase orders (Property, client's email, offer ID and offer value) and asks what property does the agent want to choose
deactivate sys

agent -> sys : chooses the property
activate sys
sys --> agent : shows property details and offers correspondent to the property and also asks what offer does the agent want to choose
deactivate sys

agent -> sys : chooses the offer
activate sys
sys --> agent : asks if the agent wants to accept or decline the offer
deactivate sys

agent -> sys : accepts or declines the offer
activate sys
sys --> agent : displays operation success
deactivate sys

deactivate agent
@enduml