@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US18 - System Sequence Diagram (SSD)

autonumber

actor "Store Manager" as manager
participant "System" as sys



activate manager

    manager -> sys: asks for a deal analysis report
    activate sys

        sys--> manager : asks to select the type of regression to use (simple or multi)
    deactivate sys

    manager -> sys: selects the type of regression
    activate sys

    opt type of regression equals to simple linear
        
        sys--> manager : asks to select only one parameter [property area (in square feet), the distance from the center (in miles), the number of \n bedrooms, the number of bathrooms or the number of parking spaces]
        deactivate sys

        manager -> sys: selects one of the parameters
        activate sys
    end
        sys--> manager : asks for parameter for prediction
        deactivate sys

    alt if type of regression equals to simple linear
                manager -> sys: inputs requested parameter
                activate sys
    else if type of regression equals to  multilinear
                manager -> sys: inputs requested parameters [property area (in square feet), the distance from the center (in miles), the number of \n bedrooms, the number of bathrooms or the number of parking spaces]
    end

    sys--> manager : shows the report for the chosen property [property values/prices (sale prices and forecast prices), the regression model \n used to estimate each value, R(SLR), R2 and R2 adjusted for SLR or MLR, confidence intervals and hypothesis tests\n for regression coefficients and significance model with Anova] and the predicted price
    deactivate sys

deactivate sys


@enduml
