@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "DealAnalysesController" as controller
participant "singleLinear : SingleLinear" as single

activate controller
                controller -> single : predictSingle(parameter)
                activate single
                single --> controller : prediction
                deactivate single
                deactivate controller
@enduml