@startuml

skinparam groupInheritance 2
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

title Project Domain Model

class UnregisteredUser {
    Cookies
}

class State {
    State name
}

class RegisteredUser {
    Username
    Password
    Name
    Passport Card Number
    Tax Number
}

class District {
    District name
}

class City {
    City name
}

class Address {
    Street
    Zip Code
}

class Contacts {
    Phone Number
    Email Adress
}

class Store {
    ID
    Designation
}

class Employee {
    Name
    ID
    Tax Number
}

class Role {
    Role
}

class Photos {
    URI
}

class AvailableEquipment {
    Equipment
}

class ComissionPercentage {
    Percentage value
}

class Rent {
    Duration of contract
}

class AnnouncementRequest {
    Initial date
}

class PublishedAnnouncement {
    Contract type
}

class Business {
    Total Price
}

class Residence {
    Number of Bedrooms
    Number of Bathrooms
    Number of Parking Spaces
}

class TypeOfProperty{
    Type
}

class Property {
    Area
    Photos
    Distance from the city center
}

class House {
    Basement
    Inhabitable loft
}

class SunExposure {
    Direction
}

class Comission {
    Value
}



@enduml