@startuml

skinparam groupInheritance 2
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0

hide circle
hide methods

title Project Domain Model

class UnregisteredUser {
    Cookies
}

class Contacts {
    Phone Number
    Email Address
}

class State {
    State name
}

class RegisteredUser {
    Username
    Password
    Name
    Passport Card Number
    Tax Number
}

class District {
    District name
}

class City {
    City name
}

class Address {
    Street
    Zip Code
}

class Contacts {
    Phone Number
    Email Adress
}

class Store {
    ID
    Designation
}

class Employee {
    Name
    ID
    Tax Number
}

class Role {
    Role
}

class Photos {
    Description
    URI
}

class AvailableEquipment {
    Equipment
}

class ComissionPercentage {
    Percentage value
}

class Rent {
    Duration of contract
}

class AnnouncementRequest {
    Initial date
}

class PublishedAnnouncement {
    Contract type
}

class Business {
    Type of Business
    Total Price
}

class Residence {
    Number of Bedrooms
    Number of Bathrooms
    Number of Parking Spaces
}

class Property {
    Area
    Photos
    Distance from the city center
}

class House {
    Basement
    Inhabitable loft
}

class SunExposure {
    Direction
}

class Comission {
    Value
}

UnregisteredUser "1" --- "1" RegisteredUser : can register as >
UnregisteredUser "*" --- "*" PublishedAnnouncement: sees >
PublishedAnnouncement "*" --- "1" Agent: publishes <
PublishedAnnouncement "1" --- "1" Business: has a <
RegisteredUser "1" --- "1" Address : can have >
RegisteredUser "1" --- "1" Contacts : has >
Comission "1" --- "1" Agent: defines <
Comission "1" --- "1" Business: contains <
Store "1" --- "1" Address: is located at >
Store "1" --- "1" Contacts: has >
Store "1" --- "*" StoreNetworkManager : manages <
State "1" --- "*" District : has >
State "1" --- "1" SystemAdministrator: adds <
City "1" --- "1" SystemAdministrator: adds <
District "1" --- "1" SystemAdministrator: adds <
SystemAdministrator "1" --- "*" Store: registers >
Employee "*" --- "1" Role : has >
Employee "1" -- "*" Store : works in >
User "1" --- "*" Property: has >
User "1" --- "1" Store: contacts >
User "1" --- "1" Business: defines >
User "1" --- "1" AnnouncementRequest: makes >
District "1" --- "*" City : has >
City "1" --- "*" Address : has >
SunExposure "1" --- "1" House: contains <
Address "1" --- "1" Property: has <
Agent "*" --- "1" Store: has <
AvailableEquipment "*" --- "1" Residence: contains <
Property "1" --- "1..30" Photos: has >
Business "1" --- "1" AnnouncementRequest: gets <


Comission <|-- ComissionPercentage
Business <|-- Rent
Employee <|-- Agent
Employee <|-- StoreNetworkManager
Employee <|-- StoreManager
Residence <|-- House
Property <|-- Residence
RegisteredUser <|-- Employee
RegisteredUser <|-- SystemAdministrator
RegisteredUser <|-- User
AnnouncementRequest  <|---  PublishedAnnouncement

@enduml