@startuml
'https://plantuml.com/class-diagram

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

class SystemAdministrator

class Employee

class SystemAdministrator{
}

class Employee{
-name
-id
-number
-agency
-tax number
-role
}

SystemAdministrator "1" - "*" Employee: registers >

@enduml