@startuml

title US20 - Domain Model


skinparam groupInheritance 2
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class Employee {
    ID
}

class Role {
    Role
}

class StoreManager{

}

class Residence {
    Number of Bedrooms
    Number of Bathrooms
    Number of Parking Spaces
}

class Property {
    Area
    Photos
    Distance from the city center
}

class TypeOfProperty{
    Type
}

class Photos {
    URI
}

class House {
    Basement
    Inhabitable loft
}

class SunExposure {
    Direction
}

class AvailableEquipment {
    Equipment
}

class User {
    Password
}

class Person {
    Name
    Email
    Phone Number
    Tax Number
    Passport Number
}

class Address {
    Street
    Zip Code
}

class City {
    City name
}

class District {
    District name
}

class State {
    State name
}

class Business {
    Requested price
}


StoreManager -|> Employee
Employee -up- Role : has >
User -|> Person
Employee -|> User

District "1" -down- "*" City : has >
State "1" -down- "*" District : has >
City "1" -down- "*" Address : has >

Property "1" --- "1" Business: has a <
Residence <|-down- House
Property <|-down- Residence
Property "1" -left-- "1..30" Photos: has >
SunExposure "1" -up- "*" House: contains <
Address "1" -left- "1" Property: has <
AvailableEquipment "*" -up- "1" Residence: contains <
TypeOfProperty "1" -down-- "1" Property: defines >

StoreManager -down- Residence : analyses >
@enduml