@startuml
'https://plantuml.com/class-diagram

title US003 - Domain Model

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
hide empty members
skinparam groupInheritance 3
hide circle

class Contacts

class SystemAdministrator

class Employee

class Role

class SystemAdministrator

class Agent

class StoreManager

class StoreNetworkManager

class Store

class Address

class Role {
Role
}

class Store {
Designation

}

class Address {
Street
Zip Code
City
Country
State
}

class SystemAdministrator {
}

class Employee {
Name
ID
Number
Tax Number
}

class Contacts {
Phone number
Email adress
}

Employee <|-- Agent
Employee <|-- StoreNetworkManager
Employee <|-- StoreManager
Employee <|-- SystemAdministrator

SystemAdministrator "1" -left- "*" Store : registers >

Store "*" - "1" Address : located at >
Employee "1" - "*" Store : works in >
Store "1" -- "1" Contacts: has >

Employee "1" -left "1" Role : has >

Store "1" -- "*" StoreNetworkManager : manages <



@enduml