@startuml
'https://plantuml.com/class-diagram

title US003 - Domain Model

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
hide empty members
skinparam groupInheritance 3
hide circle

class SystemAdministrator

class Employee

class Role

class SystemAdministrator

class Agent

class StoreManager

class StoreNetworkManager

class Store

class Address

class Role {
Role
}

class Store {
Designation

}

class Address {
Street
Zip Code
}

class District{
Name
}

class City{
Name
}

class State{
State
}

class SystemAdministrator {
}

class Employee {
Name
Email
Phone Number
Tax Number
}




Employee <|-- Agent
Employee <|-- StoreNetworkManager
Employee <|-- StoreManager
Employee <|-- SystemAdministrator

SystemAdministrator "1" -left- "*" Store : registers >

Store "*" - "1" Address : located at >
Employee "1" - "*" Store : works in >

Employee "1" -left "1" Role : has >

Store "1" -- "*" StoreNetworkManager : manages <

City "1" -- "*" Address : is in <

District "1" -- "*" City : is in <

State "1" -- "*" District :is in <

Employee "*" - Address: located at >

@enduml