@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Organization Employee" as Employee
participant ":System" as System

activate Employee

    Employee -> System : asks to create a new task
    activate System

        System --> Employee : shows task category list and asks to select one
        'System --> Employee : shows task categories list\n and requests data (reference,\ndescription,\ninformation description,\ntechnical description,\nduration, cost)
    deactivate System

    Employee -> System : selects a task category
    activate System

        System --> Employee : requests data
    deactivate System

    Employee -> System : types requested data (reference, description, \ninformal description, technical description,\nduration, cost)
    activate System

        System --> Employee : shows selected category and requested data
    deactivate System

    Employee -> System : submits data
    activate System

        System --> Employee : Shows operation success
    deactivate System
@enduml