@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US010 - System Sequence Diagram - Alternative One

autonumber

actor "Client" as Client
participant ":System" as System

activate Client

Client -> System : asks to place an offer on a property
activate System

System --> Client : shows the list of properties
deactivate System

Client -> System : selects the desired property
activate System

System --> Client : request the offer amount
deactivate System


Client -> System : submits data
activate System

System --> Client : displays operation success

@enduml