@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Unregistered User" as unregUser
participant ":System" as System

activate unregUser

    unregUser -> System : asks to create an account
    activate System

        System --> unregUser : requests data (name, passport card number, tax number, \naddress (not mandatory), email address and phone number)
    deactivate System

    alt enters Address

    unregUser -> System : types all requested data
    activate System

    else does not enter Address

    unregUser -> System : types requested data except the address

    end

        System --> unregUser : shows inserted data and asks for confirmation
    deactivate System

    unregUser -> System : confirms
    activate System

        System --> unregUser : displays operation success
    deactivate System

@enduml