@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Property owner" as Owner
participant ":System" as sys

activate Owner


    Owner -> sys : asks to create a new request for an owned property
    activate sys

    sys -> Owner : accepts the request and gives a list of possible agencies
    deactivate sys

    Owner -> sys : chooses the agency
    activate sys

    sys -> Owner : gives the chosen agency to the owner and provides a list of agents from that agency
    deactivate sys

    Owner -> sys : chooses the responsible agent
    activate sys

    sys -> Owner : gives the chosen agent to the owner and asks the type of property as well as the data from that property
    deactivate sys

    Owner -> sys : types the type of property and requested data [area in m^2, state, district, city, street, zip code and distance from city center]
    activate sys

    opt house, apartment
        Owner -> sys : types requested data [number of bedrooms, number of bathrooms, number of parking spaces, \navailable equipment (central heating and/or airconditioning)]
        opt house
            Owner -> sys : types requested data [the existence of a basement and/or inhabitable loft, sun exposure \n(North, South, East, West)]
        end
    end

    sys ---> Owner : saves all data and asks for photos of the property
    deactivate sys

    loop Sends photos (from 1 up to 30 pictures)

        Owner -> sys : sends photos of the property
        activate sys

    end

    sys ---> Owner : saves the photos and asks for the type of business and neeeded data
    deactivate sys

    alt sale
            Owner ---> sys : types the requested data [Requested price]
            activate sys
        
        else lease

            Owner ---> sys : types the requested data [Requested fee and contract duration]

    end

    sys --> Owner : retrieves the received data, displays all the information that was sent and asks to confirm the operation
    deactivate sys

    Owner -> sys : confirms the operation
    activate sys

    sys --> Owner : displays operation success
    
    @enduml