@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "User" as user
participant ":System" as sys

    activate user

    user -> sys: asks to create a new request for an owned property
    activate sys

    sys --> user : accepts the request and gives a list of possible agencies
    deactivate sys

    user -> sys : chooses the agency
    activate sys

    sys --> user : gives the chosen agency to the user and provides a list of agents from that agency
    deactivate sys

    user -> sys : chooses the responsible agent
    activate sys

    sys --> user : gives the chosen agent to the user and asks the type of property
    deactivate sys

    user -> sys : chooses the type of business
    activate sys

    sys --> user : retrieves the type of business and asks for property data
    deactivate sys

    user -> sys : types the requested data [area in m^2, state, district, city, street, zip code and distance from city center]
        activate sys
        opt house, apartment
            user -> sys : types requested data [number of bedrooms, number of bathrooms, number of parking spaces, \navailable eqsyspment (central heating and/or airconditioning)]
            opt house
                user -> sys : types requested data [the existence of a basement and/or inhabitable loft, sun exposure \n(North, South, East, West)]
            end
        end

    sys ---> user : saves all data and asks for photos of the property
    deactivate sys

    loop Sends photos one by one (from 1 up to 30 pictures)

        user -> sys : sends photos of the property
        activate sys
    end

    sys ---> user : asks for the type of business
    deactivate sys

    user -> sys : selects the type of business
    activate sys

    sys --> user : saves the type of business and asks for needed data
    deactivate sys

    user ---> sys : types the requested data [Requested price]
    activate sys

    opt rent
        user ---> sys : types the requested data [contract duration]
    end

    sys --> user : retrieves the received data and asks to confirm the operation
    deactivate sys

    user -> sys : confirms the operation
    activate sys

    sys --> user : displays operation success
    deactivate sys
    deactivate user
    @enduml