@startuml

title Sequence Diagram Partial - Get List Of Properties Using DTO

participant ":PlaceOfferController" as Controller
participant ":XMapper" as XMapper
participant "listOfPropertiesDTO:List<Properties>" as listProperties
participant "propertiesDto:PropertiesDto" as PropertiesDto

autonumber 19

activate Controller

Controller -> XMapper : toDto(listOfProperties)
activate XMapper

Group Get Property List Using DTO

XMapper -> listProperties**: create()

    loop

    XMapper -> listProperties: date = getDate()
    activate listProperties

    XMapper -[hidden]> listProperties
    deactivate listProperties

    XMapper -> listProperties: property = getProperty()
    activate listProperties

    XMapper -[hidden]> listProperties
    deactivate listProperties

    XMapper -> listProperties: typeOfBusiness = getTypeOfBusiness()
    activate listProperties

    XMapper -[hidden]> listProperties
    deactivate listProperties

    XMapper -> listProperties: propertyType = getPropertyType()
    activate listProperties

    XMapper -[hidden]> listProperties
    deactivate listProperties

    XMapper -> listProperties: business = getBusiness()
    activate listProperties

    XMapper -[hidden]> listProperties
    deactivate listProperties

    XMapper -> listProperties :agent = getAgent()
    activate listProperties

    XMapper -[hidden]> listProperties
    deactivate listProperties

    XMapper -> listProperties: durationOfContract = getDurationOfContract()
    activate listProperties

    XMapper -[hidden]> listProperties
    deactivate listProperties

    XMapper -> listProperties: comission = getComission()
    activate listProperties

    XMapper -[hidden]> listProperties
    deactivate listProperties

    XMapper -> XMapper : propertiesDto = toDto(agent,property,typeOfBusiness,propertyType,business,date,durationOfContract, comission)
    activate XMapper

    deactivate XMapper

    XMapper --> PropertiesDto**: create(...)

    XMapper -> listProperties: add(propertieDTO)
    activate listProperties

    deactivate listProperties
    end

end

XMapper --> Controller : listOfPropertiesDTO
deactivate XMapper
@enduml