@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US12

autonumber

actor "System Administrator" as Admin

activate Admin

Admin -> System : asks to import information from a legacy system
activate System

System --> Admin : shows the list of files to import
deactivate System

Admin -> System : chooses one file to import
activate System

System --> Admin : saves the information and displays operation success
deactivate System




@enduml