@startuml

title US010 - Domain Model

skinparam groupInheritance 2
skinparam monochrome true
skinparam linetype polyline
hide methods
hide circle

class Address {
Street
Zip Code
}

class AvailableEquipment {
Equipment
}


class Business {
Total price
}


class City {
City Name
}

class Comission {
Value
}
'/

class ComissionPercentage {
Percentage Value
}
'/

class Contacts {
Phone Number
Email Address
}


class District {
District Name
}


class House {
Basement
Inhabitable Loft
}

class Person {
Name
Passport Card Number
Tax Number
}

class Photos {
URI
}

class Property {
Area
Distance from the city center
}

class PublishedAnnouncement {
Contract Type

}


class Rent {
Duration of contract
}


class Residence {
Number of Bedrooms
Number of Bathrooms
Number of Parking Spaces
}


class State {
State Name
}

class SunExposure {
Direction
}

class TypeOfProperty {
Type
}

class User {
Password
}

Address "1" -- "1" Person : can have <

Business <|-- Rent

Comission "1" -- "1" Business : contains <
ComissionPercentage  --|> Comission
Contacts "1" -- "1" Person : has <

District "1" -- "*" City : has >

House "1" -- "1" SunExposure : contains >

Person <|-- User
Property <|-- Residence
Property "*" -- "1" Address : has >
PublishedAnnouncement "1" --- "1" Business : has <
Property "1" -- "1..30" Photos : has >
PublishedAnnouncement "*" --- "*" Property: advertises >

Residence "1" --- "*" AvailableEquipment : contains >
Residence <|--- House

State "1" -- "*" District : has >
State "1" -- "*" Address : has >

TypeOfProperty "1" --- "1" Property : defines >

User "*" --- "*" PublishedAnnouncement: displays >

@enduml