@startuml
'https://plantuml.com/class-diagram

class State {
 - String stateName

    +getStateName()
}

class District {
- String districtName

    +getDistrictName()
}

class City {
- String cityName

    +getCityName()
}

class Address {
    -String streetName
    -int zipCode

    +verifyZipCode()
    +getCity()
    +getDistrict()
    +getState()
    +Address(state, district, city, street, zipCode)
}

class Contacts {
    Phone Number
    Email Adress
}

class SystemAdministrator {
}

class Repositories {
    -Repositories()
    +getInstance():Repositories
    +getStateRepository()
    +getDistrictRepository()
    +getCityRepository()
}

class Store {
    -int id
    -String designation
}

class RegisterStoreController {
    +getStates()
    +getByDiscription(state)
    +getByDiscription(district)
    +registerStore(id, designation/name, state, district, city, \nstreet, zip code, email address and phone number)
}

class StateRepository {
    getState()
}

class DistrictRepository {
    getDistrict(state)
}

class CityRepository {
    getCity(district)
}

class RegisterStoreUI {

}

Repositories -> Repositories:instance
Repositories --> StateRepository: stateRepository
Repositories --> DistrictRepository: districtRepository
Repositories --> CityRepository: cityRepository
RegisterStoreController ..> Repositories : repositories
RegisterStoreUI ..> RegisterStoreController
StoresRepository --> "*" Store
Store <- "*" SystemAdministrator : registers
Address "1" -> "*"  Store : is located at
City "1" -right- "*" Address:has >
District "1" -right- "*" City : has >
State "1" -right- "*" District : has >
Contacts "1" -up--> "1" Store: has
StateRepository -left[hidden].> StateRepository

@enduml