@startuml

skinparam groupInheritance 2
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods

title US002 - Domain Model

class Property

class Comission

class Announcement

class Business

class House

class Role

class Residence

class LocationOrAdress

class AvailableEquipment

class Agent

class SunExposure

class Employee


class Agent {
}

class Residence{
    number of bedrooms
    number of bathrooms
    number of parking spaces
 }


class Property {
    area
    photos
    LocationOrAdress
    distance from the city center
}


class House {
    basement
    inhabitable loft
    SunExposure
}


class SunExposure {
    direction
}

class LocationOrAdress {
    street
    city
    county
    state
    zipCode
}

class Employee{
    name
    id
    number
    agency
    tax number
}

class Comission{
    type
    value
}

class AvailableEquipment{
equipment
}

class Business{
    total price
}

class Announcement{
    date
}

class Role{
    role
}

class Rent{
    duration of contract
    price per month
}

Residence <|--- House
Property <|--- Residence
Business <|--- Rent

Business "*" --- "1" Comission : contains >
Business "1" --- "1" Property : have a >

Business  <|---  Announcement

Property "*" --- "1" Agent: publishes <
Property "*" --- "1" LocationOrAdress : located at >

House "*" --- "1" SunExposure : contains >

AvailableEquipment "*" --- "1" Residence: has >

Role "1" --- "*" Employee : has <

Agent "*" --- "1" LocationOrAdress : has >
Agent <|---- Employee
Agent "1" --- "1" Comission : defines >




@enduml