@startuml

skinparam groupInheritance 2

class Property

class Comission

class Announcement

class Business

class House

class Role

class Residence

class LocationOrAdress

class AvailableEquipment

class Agent

class SunExposure

class Employee


class Agent {
}

class Residence{
    -number of bedrooms
    - number of bathrooms
    - number of parking spaces
 }


class Property {
    - area
    - photos
    - LocationOrAdress
    - distance from the city center
    - the requested price
}


class House {
    - basement
    - inhabitable loft
    - SunExposure
}


class SunExposure {
    - regions
}

class LocationOrAdress {
    -street
    -adressExtension
    -zipCode
}

class Employee{
    -name
    -id
    -number
    -agency
    -tax number
}

class Comission{
    -type
    -value
}

class AvailableEquipment{
-equipment
}

class Business{
-sale
-rent
}

class Announcement{
-date
}

class Role{
-role
}

Residence <|--- House
Property <|--- Residence

Business "*" --- "1" Comission : contains >
Business "1" --- "1" Property : have a >

Business  <|---  Announcement

Property "*" --- "1" Agent: publishes <
Property "*" --- "1" LocationOrAdress : located at >

House "*" --- "1" SunExposure : contains >

AvailableEquipment "*" --- "1" Residence: has >

Role "1" --- "*" Employee : has <

Agent "*" --- "1" LocationOrAdress : has >
Agent <|---- Employee
Agent "1" --- "1" Comission : defines >




@enduml