@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US015

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

    Agent -> System : asks to list all booking requests for properties managed by him
    activate System

        System --> Agent : requests to select an initial date
    deactivate System

    Agent -> System : selects an initial date
    activate System

        System --> Agent : requests to select an end date
        deactivate System

    Agent -> System : selects an end date
    activate System

        System --> Agent : shows all booking requests sorted by date in ascending order \nand displays operation success
    deactivate System

@enduml