@startuml
 skinparam monochrome true
 skinparam packageStyle rectangle
 skinparam shadowing false

 autonumber

 title Sequence Diagram Split - US015

 'hide footbox
 actor "Agent" as Agent
 participant ":DisplayMessageUI" as UI
 participant ":DisplayMessageController" as CTRL
 participant ":Repositories" as Repository
 participant "repositories\n:Repositories" as repository2
 participant "messageRepository:\nMessageRepository" as MessageRepository
 participant ":ApplicationSession" as app
 participant "appSession\n:ApplicationSession" as APP
 participant "currentSession\n:UserSession" as User
 participant "employeeRepository\n:Employee Repository" as Employee
 participant ":XMapper" as Mapper
 participant "listOfMessagesDTO:List<Messages>" as listMessagesDTO
 participant "listOfMessages:List<Messages>" as listMessages


 activate Agent

         Agent -> UI : asks to list all booking requests for properties managed by him

         activate UI

             UI -> CTRL** : create

              UI --> Agent : requests an initial date and an end date for list the requests
              deactivate UI

              Agent -> UI :  types requested data (begin date, end date)
              activate UI

              UI -> CTRL : getListBooking()
              activate CTRL

                ref over CTRL

                    Get Employee By Email

                end


             ref over CTRL

             Get Message List By Agent And Date

             end

             autonumber 21

             CTRL -> Mapper : toDTO(messageListByAgentAndDate)
             activate Mapper

             ref over Mapper

             Get Message By Agent And Date DTO

             end

             autonumber 38

             Mapper --> CTRL : messageListByAgentAndDate
             deactivate Mapper

             CTRL --> UI : messageListByAgentAndDate
             deactivate CTRL

         UI --> Agent : shows all booking requests sorted by date in ascending order\nand requests confirmation
     deactivate UI

         Agent -> UI : submits data
         activate UI

         UI --> Agent : displays operation success
     deactivate Agent


 @enduml