@startuml

participant ":ListDealsController" as ListDealsController
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "offerRepository\nOfferRepository" as OfferRepository

autonumber  26

Group getDealsByDescendingArea

activate ListDealsController

                ListDealsController -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> ListDealsController: repositories
                deactivate RepositorySingleton

                ListDealsController -> PLAT : getOfferRepository()
                activate PLAT

                    PLAT --> ListDealsController: offerRepository
                deactivate PLAT

                ListDealsController -> OfferRepository : getDealsByDescendingArea()
                activate OfferRepository

                    OfferRepository --> ListDealsController : offersListMade
                deactivate OfferRepository

end

@enduml