@startuml
'https://plantuml.com/sequence-diagram


participant ":ListDealsController" as ListDealsController
participant ":OfferMapper" as OfferMapper
participant "listOfferDTO:List<OfferDTO>" as ListOfferDto
participant "listOffer:List<Offer>" as ListOffer
participant "offerDto:OfferDto" as OfferDto


autonumber 32

activate ListDealsController


ListDealsController --> OfferMapper : toDto(offersListMade)
                activate OfferMapper
Group Get DTO Deals


                OfferMapper -> ListOfferDto** : create(...)
loop
                OfferMapper -> ListOffer : orderAmount = getOrderAmount()
                activate ListOffer
                deactivate ListOffer

                OfferMapper -> ListOffer : publishedAnnouncement = getPublishedAnnouncement()
                activate ListOffer
                deactivate ListOffer

                 OfferMapper -> ListOffer : name = getName()
                 activate ListOffer
                 deactivate ListOffer

                 OfferMapper -> ListOffer: offerState = getOfferState()
                 activate ListOffer
                 deactivate ListOffer

                 OfferMapper -> OfferMapper: offerDTO = toDtoObject(orderAmount,name,offerState,publishedAnnouncement)
                 activate OfferMapper
                 deactivate OfferMapper

                 OfferMapper --> OfferDto**: create(..)

                 OfferMapper -> ListOfferDto: add(OfferDto)
                 activate ListOfferDto
                 deactivate ListOfferDto
      end
end
               OfferMapper --> ListDealsController: offersDTOListMade
            deactivate ListDealsController


@enduml