@startuml
'https://plantuml.com/sequence-diagram

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US09 - Sequence Diagram Partial - Get User Identity

autonumber

'hide footbox
participant ":SendMessageController" as CTRL
participant ":Repositories" as Repository
participant "repositories\n:Repositories" as Repository2
participant "UserRepository:\nUser Repository" as UserRepository


autonumber

-> CTRL : getUserInformation()

            activate CTRL

            CTRL -> Repository : getInstance()
                activate Repository

            Repository --> CTRL : repositories
                deactivate Repository

            CTRL -> Repository2 : getUserInformationRepository()
                activate Repository2

            Repository2 --> CTRL : UserInformationRepository
                deactivate Repository2

            CTRL -> UserRepository : getUserInformation()

                activate UserRepository

            UserRepository --> CTRL : User Information

                deactivate UserRepository

         <-- CTRL : User Information
@enduml