@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "System Administrator" as Admin
participant ":System" as System

activate Admin

    Admin -> System : asks to register an employee
    activate System

    System --> Admin : shows list of roles and asks to select one
    deactivate System

        Admin -> System : selects a user role
        activate System

         System --> Admin : shows list of stores and asks to select one
            deactivate System

                Admin -> System : selects a user role
                activate System

   System --> Admin :  requested data(name,passport,tax number \n,adress,email adress,telephone number).
     deactivate System

    Admin -> System : types requested data
    activate System

     System --> Admin : shows the information of an employee
            deactivate System

    Admin -> System : submits data
    activate System

        System --> Admin : displays operation success
    deactivate System

@enduml