@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title US016 - System Sequence Diagram - Alternative One

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent

Agent -> System : asks to see the schedule requests
activate System

System --> Agent : shows the schedule requests
deactivate System

Agent -> System : selects a schedule request to respond
activate System

System --> Agent : shows the desired schedule request
deactivate System

Agent -> System : responds to the schedule request
activate System

System --> Agent : receives the agent's response and sends email
deactivate System

Agent -> System : submits data
activate System

System --> Agent : display operation success
deactivate System

@enduml