@startuml


'https://plantuml.com/class-diagram

class AddEmployeeUI

class Adress

class Contacts

class AddEmployeeController

class Repositories

class Employee

class Store

class Role

class SystemAdministrator

class StoresRepository

class EmployeeListOfRolesRepository


class Adress{
-String street
-int zipCode
-String city
-String country
-String state
}


class Contacts{
-email
-phone number
}

class Role{
-String role
+Role(role)
}

class SystemAdministrator{
}

class Employee{
-String name
-Passport passport
-int Tax Number
+Employee(name,citizen´s card number,tax number ,adress,email adress,telephone number,agency  role,createdBy)
}

class StoresRepository{
+getStores()

}

class EmployeeListOfRolesRepository{
+getRolesEmployee()

}

class AddEmployeeUI{
}

class AddEmployeeController{
+AddEmployeeController(employeeRoleListRepository,StoresRepository)
+getRolesEmployee()
+getStores()
+addEmployee(name,citizen´s card number,tax number ,adress,email adress,telephone number,store, role)
-getRolesEmployeeByDescription(roleEmployeeDescription)
}

class Repositories{
-Repositories()
+getInstance():Repositories
+getRolesEmployeeRepository()
+getStoresRepository()
}

class Store{
-String name
-Adress adress
-Contacts contact
-addEmployee(employee)
-validateTask(employee)
+Store(name,adress,contact)
+addEmployee(name,citizen´s card number,tax number ,adress,email adress,telephone number,agency  role)
}


AddEmployeeUI .> AddEmployeeController

AddEmployeeController ..> "1" Store : store

AddEmployeeController ...> EmployeeListOfRolesRepository :EmployeeListOfRolesRepository

AddEmployeeController ..> StoresRepository : StoresRepository

Store "1" ---> "*" Employee : employee

Repositories -> Repositories:intance

Repositories ---> StoresRepository: storeRepository

Repositories ----> EmployeeListOfRolesRepository:roleEmployee

AddEmployeeController .>  Repositories : repositories

StoresRepository --> "*" Store

Employee <|-- SystemAdministrator

Store <- "*" SystemAdministrator : registers

EmployeeListOfRolesRepository ---> Role

Employee "1" -> "1" Role : role

Employee "1" --> "1" Contacts

Adress "1" -> "*"  Store

Adress "1" --> "*" Employee

@enduml