@startuml
'https://plantuml.com/class-diagram

class AddEmployeeUI

class Adress

class AddEmployeeController

class Repositories

class Employee

class Store

class Role

class SystemAdministrator

class StoresRepository

class EmployeeListOfRolesRepository

class State

class City

class District

class StateRepository

class State{
 - String stateName

    +getStateName()
}

class District{
- String districtName

    +getDistrictName()
}

class City{
- String cityName

    +getCityName()
}

class Adress{
 -String streetName
    -int zipCode

    +verifyZipCode()
    +getCity()
    +getDistrict()
    +getState()
    +Address(state, district, city, street, zipCode)
}

class Role{
-String role
+Role(role)
}

class SystemAdministrator{
}

class Employee{
-String name
-Passport passport
-int Tax Number
+Employee(name,citizen´s card number,tax number ,adress,email adress,telephone number,agency  role,createdBy)
}

class StoresRepository{
+getStores()

}

class EmployeeListOfRolesRepository{
+getRolesEmployee()

}

class AddEmployeeUI{
}

class AddEmployeeController{
+AddEmployeeController(employeeRoleListRepository,StoresRepository)
+getRolesEmployee()
+getStores()
+addEmployee(name,citizen´s card number,tax number ,adress,email adress,telephone number,store, role)
-getRolesEmployeeByDescription(roleEmployeeDescription)
}

class Repositories{
-Repositories()
+getInstance():Repositories
+getRolesEmployeeRepository()
+getStoresRepository()
}

class Store{
-String name
-addEmployee(employee)
-validateEmployee(employee)
+Store(name,adress,contact)
+addEmployee(name,citizen´s card number,tax number ,adress,email adress,telephone number,agency  role)
}


AddEmployeeUI .> AddEmployeeController

AddEmployeeController ..> "1" Store : store

AddEmployeeController ...> EmployeeListOfRolesRepository :EmployeeListOfRolesRepository

AddEmployeeController ..> StoresRepository : StoresRepository

Store "1" ---> "*" Employee : employee

Repositories -> Repositories:intance

Repositories ---> StoresRepository: storeRepository

Repositories ----> EmployeeListOfRolesRepository:roleEmployee

AddEmployeeController .>  Repositories : repositories

StoresRepository --> "*" Store

Employee <|-- SystemAdministrator

Store <- "*" SystemAdministrator : registers

EmployeeListOfRolesRepository ---> Role

Employee "1" -> "1" Role : role

Adress "1" -> "*"  Store

Adress "1" --> "*" Employee

Adress "*" -left- "1" City:is in >

City "*" -left- "1" District : is in >

District "*" -left- "1" State : is in >

AddEmployeeController ..> "1" StateRepository : StateRepository

Repositories -> StateRepository: storeRepository

StateRepository -left[hidden].> StateRepository

@enduml