@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Sequence Diagram (SD)

autonumber

actor "System Administrator" as Admin
participant ":AddEmployeeUI" as AddEmployeeUI
participant ":AddEmployeeController" as AddEmployeeController
participant ":Repositories" as Singleton
participant "repositories\n:Repositories" as repositories
participant "employeeRolesRepository\n:EmployeeRolesRepository" as EmployeeRolesRepository
participant "storesRepository\n:StoreListRepository" as StoreRepository
participant ":Store" as Store
participant "employee\n:Employee" as Employee


activate Admin

     Admin -> AddEmployeeUI : asks to register an employee
        activate AddEmployeeUI

        AddEmployeeUI -> AddEmployeeController** : create

        AddEmployeeUI -> AddEmployeeController : getsRolesEmployee()
        activate AddEmployeeController

        AddEmployeeController -> Singleton : getInstance()
        activate Singleton

        Singleton --> AddEmployeeController: repositories
        deactivate Singleton

        AddEmployeeController -> repositories : getEmployeeRolesRepository()
        activate repositories

        repositories --> AddEmployeeController : employeeRolesRepository
        deactivate repositories

        AddEmployeeController -> EmployeeRolesRepository : getRolesEmployee()
        activate EmployeeRolesRepository

        EmployeeRolesRepository --> AddEmployeeController: rolesEmployee
        deactivate EmployeeRolesRepository


         AddEmployeeController --> AddEmployeeUI : rolesEmployee
                deactivate AddEmployeeController

        AddEmployeeUI --> Admin : shows list of roles and asks to select one
        deactivate AddEmployeeUI

            Admin -> AddEmployeeUI : selects the role of the employee
            activate AddEmployeeUI

                AddEmployeeUI --> AddEmployeeUI: keepsRoles(roleEmployeeDescription)

      AddEmployeeUI -> AddEmployeeController : getStores()
        activate AddEmployeeController

         AddEmployeeController -> Singleton : getInstance()
                activate Singleton

                Singleton --> AddEmployeeController: repositories
                deactivate Singleton

                AddEmployeeController -> repositories : getStoreRepository()
                activate repositories

                repositories --> AddEmployeeController : getStoreRepository
                deactivate repositories

                AddEmployeeController -> StoreRepository : getStore()
                activate StoreRepository

                 StoreRepository --> AddEmployeeController: stores
                deactivate StoreRepository

         AddEmployeeController --> AddEmployeeUI : stores
                deactivate AddEmployeeController

             AddEmployeeUI --> Admin : shows list of stores and asks to select one
                deactivate AddEmployeeUI

                    Admin -> AddEmployeeUI : selects a store
                    activate AddEmployeeUI

AddEmployeeUI --> AddEmployeeUI: keepsStores(storeDescription)


       AddEmployeeUI --> Admin :  requested data(name,citizen´s card number,tax number \n,adress,email adress,telephone number).
         deactivate AddEmployeeUI

    Admin -> AddEmployeeUI : types requested data
    activate AddEmployeeUI

    AddEmployeeUI --> AddEmployeeUI: keeps data (name,citizen´s card number,tax number \n,adress,email adress,telephone number,storeDescription\n roleDescription)

    AddEmployeeUI --> Admin : shows the information of an employee
        deactivate AddEmployeeUI

    Admin -> AddEmployeeUI : submits data
    activate AddEmployeeUI

    AddEmployeeUI -> AddEmployeeController: addEmployee (name,citizen´s card number,tax number \n,adress,email adress,telephone number,agencyDescription\n roleDescription)
      activate AddEmployeeController

    AddEmployeeController -> AddEmployeeController: getRoleByDescription(roleDescription)
    activate AddEmployeeController

    AddEmployeeController -> Singleton: getInstance()
    activate Singleton

    Singleton --> AddEmployeeController :repositories
    deactivate Singleton

    AddEmployeeController -> repositories: getEmployeeRolesRepository()
    activate repositories

    repositories--> AddEmployeeController:employeeRolesRepository
    deactivate repositories

    AddEmployeeController -> EmployeeRolesRepository: getsRolesEmployeeByDescription()
    activate EmployeeRolesRepository

    EmployeeRolesRepository --> AddEmployeeController: roleEmployee
    deactivate EmployeeRolesRepository

    AddEmployeeController --> AddEmployeeController: roleEmployee



    AddEmployeeController -> AddEmployeeController: getStoresByDescription(roleDescription)
    activate AddEmployeeController

    AddEmployeeController -> Singleton: getInstance()
    activate Singleton

    Singleton --> AddEmployeeController :repositories
    deactivate Singleton

    AddEmployeeController -> repositories: getStoresRepository()
    activate repositories

    repositories--> AddEmployeeController:StoreRepository
    deactivate repositories

    AddEmployeeController -> StoreRepository: getsStoreByDescription()
    activate EmployeeRolesRepository

    EmployeeRolesRepository --> AddEmployeeController: store
    deactivate EmployeeRolesRepository

    AddEmployeeController --> AddEmployeeController: store

         AddEmployeeController --> Store: addEmployee (name,citizen´s card number,tax number \n,adress,email adress,telephone number,agency\n role)
            activate Store

            Store -> Employee** : addEmployee (name,citizen´s card number,tax number \n,adress,email adress,telephone number,agency\n role)
             Store -> Store : addEmployee(employee)
             activate Store
              Store -> Store : validateEmployee(employee)
              activate Store
               Store --> Store
               deactivate Store
                Store--> Store
                deactivate Store

       Store --> AddEmployeeController: employee
            deactivate Store

    AddEmployeeController --> AddEmployeeUI: employee
      deactivate AddEmployeeController

    AddEmployeeUI --> Admin : displays operation success
      deactivate AddEmployeeUI


@enduml
